--- Auto generated by 'aubo_scope' v0.31.0-alpha.58 2024-08-15 13:18:05
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math
local realtime = aubo.realtime or realtime

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_A8145()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(1)
    setHardwareCustomParameters("[over_force_config] \n    is_enable =true")
    setHardwareCustomParameters("handle_enable=false")
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    gripper_service = sched.jsonrpc.proxy('http://127.0.0.1:8890/jsonrpc')
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    modbusAddSignal("/dev/ttyUSB0,115200,N,8,1", 9, 1000, 3, "control", false)
    modbusAddSignal("192.168.192.5,502", 1, 0, 3, "agvGo", true)
    modbusAddSignal("192.168.192.5,502", 1, 18, 0, "agvOK", true)
    modbusAddSignal("192.168.192.5,502", 1, 8, 2, "agvOver", true)
    setPayload(0, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    u5e73u9762_0= {}
    tableUp = 0
    tableGet = 0
    point_get = 0
    point_up = 0
    gdddd = 0
    PUT22 = 0
    PutUpJointRad = {}
    PutJointRad = {}
    setLabel(1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    PUT0_p = {-0.09405717358581661,0.5149632598665251,0.2202961926323803,1.556596241049699,0.4241110803791184,3.12235354228847}    
    PUT0_q = {-1.633479379185494,0.6357279473537837,-2.026986760880853,-2.675672396205753,-1.521512702082548,-0.4235141852420735}    
    pzd4_p = {-0.07888439999566645,0.5250757253967675,0.6029207922775044,2.97319780134579,0.1168737101306469,-2.713720538501295}    
    pzd4_q = {-1.649042215863138,0.1279655240885559,-1.039559524460714,0.1995077129896815,-1.59009382230038,-0.5179659072086543}    
    gdddd_0_p = {-0.09156756597549007,0.5546094880319538,0.5111636565875596,2.123370195132839,0.3412762355732998,-2.943977860105963}    
    gdddd_0_q = {-1.63349162615514,0.1083397552308542,-1.62002302128696,-1.210284191125561,-1.521454013633947,-0.4234151484850601}    
    
    setLabel(2, "机器人编程")
    setLabel(3, "tableUp:=0")
    sched.INST([[ tableUp = 0 ]], _ENV)
    
    setLabel(4, "funcA.lua")
    --subscript context start
    --分割字符串函数输出列表
    function string.split(str,delimiter)
    	if str  ==  nil or str ==  ''  or  delimiter  == nil then
       return  nil
    	end
    	local  result =  {}
    	for match in  (str..delimiter):gmatch("(.-)"..delimiter) do
       table.insert(result,match)
    	end
    	return result
    end
    
    --自定义函数区
    pi = 3.1416
    --弧度转换函数单个
    function toRad(degs)
        if degs==nil or degs=="" then
            return nil
        end
        return degs*(pi/180) 
    end
    -- 弧度转角度单个
    function toDeg(rads)
        if rads==nil or rads =="" then
            return nil
        end
        return rads*(180/pi)
    end
    
    -- 将角度列表转换为弧度列表
    function degToRadList(degrees)
        local radians = {}
        for i,j in ipairs(degrees) do
            radians[i] =j*(pi/180)
        end
        return radians
    end
    
    -- 将弧度列表转换为角度列表
    function radToDegList(radians)
        local degrees = {}
        for a,b in ipairs(radians) do
            degrees[a] =b*(180/pi)
        end
        return degrees
    end
    ---------------------------------------
    --subscript context end
    
    setLabel(5, "tableGet:=0")
    sched.INST([[ tableGet = 0 ]], _ENV)
    
    setLabel(6, "point_get:=0")
    sched.INST([[ point_get = 0 ]], _ENV)
    
    setLabel(7, "point_up:=0")
    sched.INST([[ point_up = 0 ]], _ENV)
    
    setLabel(8, "关节运动")
    setLabel(9, "pzd4")
    setTcpOffset({0,0,0,0,0,0})
    moveJoint(inverseKinematics(pzd4_q, pzd4_p), 1.39626, 1.0472, 0, 0)
    
    setLabel(10, "fput1.lua")
    --subscript context start
    ip = "192.168.192.111" --服务端IP地址
    port = 55000 --串口号
    client_name = "socketPujmm1" --客户端名称
    socketOpen(ip, port, client_name) ----与服务端建立通信
    sleep(2)
    --------------------------------------通信部分----------------------------------------------
    -- 发送拍照数据
    msg_send_put01="201,1,-94.48,7.33,-59.56,11.43,-91.11,-29.68,-78.88,525.08,602.92,170.34,6.7,-155.5"
    socketSendLine(msg_send_put01, client_name) --发送给服务端字符串
    sleep(2)
    msg_send_put02="203,10,2"
    socketSendLine(msg_send_put02, client_name) --发送给服务端字符串
    sleep(2)
    msg_send_put03="205,1"
    socketSendLine(msg_send_put03, client_name) --发送给服务端字符串
    sleep(1)
    --接受数据
    rec_str = ""
    rec_key = "camera_send2" --接收服务端发送的字符串
    --接收服务端发送的字符串后停止循环
    while(rec_str == nil or rec_str == "") 
    do
      socketReadString(rec_key, client_name, "", "", true) 
      rec_str = getString(rec_key, "")
    end
    ------------------------------数据处理--------------------------------
    --------------------------------------------------------
    GddADeg={-93.59,23.09,-114.39,-139.07,-87.17,-24.26}
    GddARad=degToRadList(GddADeg)
    sleep(0.001)
    pzdDeg={-94.48,7.33,-59.56,11.43,-91.11,-29.86}
    pzdRad=degToRadList(pzdDeg)
    textmsg("start running ...")
    sleep(0.001)
    --机械臂移动参数设置区
    pointPutAll=string.split(rec_str,",")
    point_get=rec_str
    -- textmsg("up point")
    -- textmsg(pointPutAll[7])
    -- textmsg(pointPutAll[12])
    -- textmsg("get point")
    -- textmsg(pointPutAll[15])
    -- textmsg(pointPutAll[20])
    -- textmsg(point_get)
    ----------------------------------------------------
    PutUpJointDeg0={pointPutAll[8],pointPutAll[9],pointPutAll[10],pointPutAll[11],pointPutAll[12],pointPutAll[13]}
    PutJointDeg0={pointPutAll[16],pointPutAll[17],pointPutAll[18],pointPutAll[19],pointPutAll[20],pointPutAll[21]}
    -- PutUpJointRad={toRad(pointPutAll[7]),toRad(pointPutAll[8]),toRad(pointPutAll[9]),toRad(pointPutAll[10]),toRad(pointPutAll[11]),toRad(pointPutAll[12])}
    -- PutJointRad={toRad(pointPutAll[15]),toRad(pointPutAll[16]),toRad(pointPutAll[17]),toRad(pointPutAll[18]),toRad(pointPutAll[19]),toRad(pointPutAll[20])}
    sleep(0.001)
    PutUpJointRad=degToRadList(PutUpJointDeg0)
    PutJointRad=degToRadList(PutJointDeg0)
    textmsg("PutUpJointRad result")
    textmsg(table.concat(PutUpJointRad,","))
    textmsg("PutUpJointDeg result")
    textmsg(table.concat(PutUpJointDeg0,","))
    sleep(0.001)
    textmsg("PutJointRad result")
    textmsg(table.concat(PutJointRad,","))
    textmsg("PutJointDeg result")
    textmsg(table.concat(PutJointDeg0,","))
    sleep(0.01)
    ---------------------------主控部分--------------------------------
    --机械臂移动控制区
    moveJoint(GddARad, 1.0, 1.0, 0, 0)
    --视觉伺服点
    moveJoint(PutUpJointRad, 1.0, 1.0, 0, 0)
    moveJoint(PutJointRad,1.0, 1.0, 0, 0)
    sleep(2)
    --放置
    modbusSetOutputSignal('control', 811)
    sleep(1)
    --视觉伺服点
    moveJoint(PutUpJointRad,1.0, 1.0, 0,0)
    moveJoint(GddARad, 1.0, 1.0, 0, 0)
    moveJoint(pzdRad, 1.0, 1.0, 0, 0)
    ----------------------------------------------------
    socketClose(client_name)
    textmsg("running finish")
    --subscript context end
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_A8145()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


