--- Auto generated by 'aubo_scope' v0.31.0-alpha.58 2024-08-12 10:56:28
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math
local realtime = aubo.realtime or realtime

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_bdbd()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(0)
    setHardwareCustomParameters("[over_force_config] \n    is_enable =false")
    setHardwareCustomParameters("handle_enable=false")
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    gripper_service = sched.jsonrpc.proxy('http://127.0.0.1:8890/jsonrpc')
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    modbusAddSignal("/dev/ttyUSB0,115200,N,8,1", 9, 1000, 3, "control", false)
    modbusAddSignal("192.168.192.5,502", 1, 0, 3, "agvGo", true)
    modbusAddSignal("192.168.192.5,502", 1, 18, 0, "agvOK", true)
    modbusAddSignal("192.168.192.5,502", 1, 8, 2, "agvOver", true)
    setPayload(0, {0,-0.1,-0.08}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    u5e73u9762_0= {}
    setLabel(1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    u8defu70b9_0_p = {-0.1676978427803161,0.5309919497637373,0.6421765453995324,3.141450915147931,-4.055181615872677e-05,-2.694400763315001}    
    u8defu70b9_0_q = {-1.484868526016207,0.3657771806744229,-0.5361570223894596,0.6687438677196553,-1.570708294121996,-0.361264081417031}    
    u8defu70b9_1_p = {-0.1677139477723146,0.4110469353718814,0.6421946340807133,3.141179533036807,4.749643082733605e-05,-2.694621208061442}    
    u8defu70b9_1_q = {-1.460637896571613,0.02473275520008025,-0.9653612588604734,0.5802967076505227,-1.570704626093958,-0.3368130065188085}    
    u8defu70b9_2_p = {-0.03790405092543134,0.410999696771514,0.6422704289701612,3.140951199625855,0.0002053391642201026,-2.694247556787017}    
    u8defu70b9_2_q = {-1.777684385024634,-0.05426326075897776,-1.042676378235619,0.5817492467533874,-1.570568909056569,-0.6542294807751208}    
    u8defu70b9_3_p = {-0.04307252109340862,0.535756636565755,0.6424386178902169,3.140933215428774,0.0001851421777502147,-2.694250372971533}    
    u8defu70b9_3_q = {-1.718635620876486,0.2962878749030659,-0.6358197996261286,0.6380388050174319,-1.570579913140682,-0.5951815654268483}    
    u8defu70b9_4_p = {-0.1031926128270681,0.4755541489718946,0.6434094603180334,3.13963991420252,0.001060176504014809,-2.694423418811009}    
    u8defu70b9_4_q = {-1.609460009967292,0.1412871653209834,-0.8329164056238961,0.5943709312305526,-1.570822002991159,-0.4858339815998292}    
    
    setLabel(2, "机器人编程")
    setLabel(3, "关节运动")
    setLabel(4, "路点_0")
    moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.39626, 1.0472, 0, 0)
    
    setLabel(5, "路点_1")
    moveJoint(inverseKinematics(u8defu70b9_1_q, u8defu70b9_1_p), 1.39626, 1.0472, 0, 0)
    
    setLabel(6, "路点_2")
    moveJoint(inverseKinematics(u8defu70b9_2_q, u8defu70b9_2_p), 1.39626, 1.0472, 0, 0)
    
    setLabel(7, "路点_3")
    moveJoint(inverseKinematics(u8defu70b9_3_q, u8defu70b9_3_p), 1.39626, 1.0472, 0, 0)
    
    setLabel(8, "路点_4")
    moveJoint(inverseKinematics(u8defu70b9_4_q, u8defu70b9_4_p), 1.39626, 1.0472, 0, 0)
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_bdbd()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


