--- Auto generated by 'aubo_scope' v0.31.0-alpha.58 2024-08-09 16:56:04
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math
local realtime = aubo.realtime or realtime

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_MMM()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(2)
    setHardwareCustomParameters("[over_force_config] \n    is_enable =true")
    setHardwareCustomParameters("handle_enable=false")
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    gripper_service = sched.jsonrpc.proxy('http://127.0.0.1:8890/jsonrpc')
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    modbusAddSignal("/dev/ttyUSB0,115200,N,8,1", 9, 1000, 3, "control", false)
    modbusAddSignal("192.168.192.5,502", 1, 0, 3, "agvGo", true)
    modbusAddSignal("192.168.192.5,502", 1, 18, 0, "agvOK", true)
    modbusAddSignal("192.168.192.5,502", 1, 8, 2, "agvOver", true)
    setPayload(0, {0,-0.1,-0.08}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    setTcpOffset({0,0.1,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    u5e73u9762_0= {}
    setLabel(1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    center_p = {-0.5439802714619596,-0.01220747993595928,0.4476793938407289,-3.141417243138524,-7.174244404937657e-05,-1.15945459912321}    
    center_q = {-0.3327471035391832,-0.1022468878319733,-1.63621045341655,0.03701040289874955,-1.570862351299572,-0.7440888316387051}    
    
    setLabel(2, "机器人编程")
    setLabel(3, "直线运动")
    setLabel(4, "center")
    moveLine(center_p, 0.5, 0.3, 0, 0)
    
    handler_thread_move_5=thread(function()
        setLabel(5, "方向:基座 X+")
        -- enter_critical
        sched.INST([[flag_thread_move_5 = 1]], _ENV)
        towardsPos=calculate_point_to_move_towards(u57fau5ea7, {1.0,0.0,0.0}, 0.03)
        moveLine(towardsPos, 0.5, 0.3, 0, 0)
        sched.INST([[flag_thread_move_5 = 2]], _ENV)
        -- exit_critical
    end, "thread_move_5")
    
    flag_thread_move_5 = 0
    run(handler_thread_move_5)
    while true do
        setLabel(6, "直到固定距离：30 mm")
        sleep(1e-10)
        if (flag_thread_move_5 > 1) then
            kill(handler_thread_move_5)
            break
        end
        sync()
    end
    
    setLabel(7, "center")
    moveLine(center_p, 0.5, 0.3, 0, 0)
    
    handler_thread_move_8=thread(function()
        setLabel(8, "方向:基座 X+")
        -- enter_critical
        sched.INST([[flag_thread_move_8 = 1]], _ENV)
        towardsPos=calculate_point_to_move_towards(u57fau5ea7, {1.0,0.0,0.0}, 0.06)
        moveLine(towardsPos, 0.5, 0.3, 0, 0)
        sched.INST([[flag_thread_move_8 = 2]], _ENV)
        -- exit_critical
    end, "thread_move_8")
    
    flag_thread_move_8 = 0
    run(handler_thread_move_8)
    while true do
        setLabel(9, "直到固定距离：60 mm")
        sleep(1e-10)
        if (flag_thread_move_8 > 1) then
            kill(handler_thread_move_8)
            break
        end
        sync()
    end
    
    setLabel(10, "center")
    moveLine(center_p, 0.5, 0.3, 0, 0)
    
    setLabel(11, "直线运动")
    setLabel(12, "center")
    moveLine(center_p, 0.5, 0.3, 0, 0)
    
    handler_thread_move_13=thread(function()
        setLabel(13, "方向:基座 X-")
        -- enter_critical
        sched.INST([[flag_thread_move_13 = 1]], _ENV)
        towardsPos=calculate_point_to_move_towards(u57fau5ea7, {-1.0,0.0,0.0}, 0.03)
        moveLine(towardsPos, 0.5, 0.3, 0, 0)
        sched.INST([[flag_thread_move_13 = 2]], _ENV)
        -- exit_critical
    end, "thread_move_13")
    
    flag_thread_move_13 = 0
    run(handler_thread_move_13)
    while true do
        setLabel(14, "直到固定距离：30 mm")
        sleep(1e-10)
        if (flag_thread_move_13 > 1) then
            kill(handler_thread_move_13)
            break
        end
        sync()
    end
    
    setLabel(15, "center")
    moveLine(center_p, 0.5, 0.3, 0, 0)
    
    handler_thread_move_16=thread(function()
        setLabel(16, "方向:基座 X-")
        -- enter_critical
        sched.INST([[flag_thread_move_16 = 1]], _ENV)
        towardsPos=calculate_point_to_move_towards(u57fau5ea7, {-1.0,0.0,0.0}, 0.06)
        moveLine(towardsPos, 0.5, 0.3, 0, 0)
        sched.INST([[flag_thread_move_16 = 2]], _ENV)
        -- exit_critical
    end, "thread_move_16")
    
    flag_thread_move_16 = 0
    run(handler_thread_move_16)
    while true do
        setLabel(17, "直到固定距离：60 mm")
        sleep(1e-10)
        if (flag_thread_move_16 > 1) then
            kill(handler_thread_move_16)
            break
        end
        sync()
    end
    
    setLabel(18, "center")
    moveLine(center_p, 0.5, 0.3, 0, 0)
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_MMM()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


