--- Auto generated by 'webscope' 0.31.0-alpha.58 2024-10-17 13:36:45
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math
local realtime = aubo.realtime or realtime

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt



app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_Untitled_0()
    local _ENV = sched.select_robot(1)
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8990/jsonrpc')
    setCollisionStopType(1)
    setCollisionLevel(2)
    setHardwareCustomParameters("[over_force_config] \n is_enable = true")
    setHomePosition({0,-0.26179938779914946,1.7453292519943295,0.4363323129985824,1.5707963267948966,0})
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    modbusAddSignal("/dev/ttyUSB0,115200,N,8,1",9,1000,3,"control",false)
    modbusAddSignal("192.168.192.5,502",1,0,3,"agvGo",false)
    modbusAddSignal("192.168.192.5,502",1,18,0,"agvOK",false)
    modbusAddSignal("192.168.192.5,502",1,8,2,"agvOver",false)
    setPayload(3, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    setTcpOffset({0,0,0,0,0,0})
    sleep(0)
    setToolVoltageOutputDomain(0)
    setToolIoInput(0,true)
    setToolIoInput(1,true)
    setToolIoInput(2,true)
    setToolIoInput(3,true)
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    setHardwareCustomParameters("handle_enable=false")
    tableUp = 0
    tableGet = 0
    point_get = 0
    point_up = 0
    gdddd = 0
    PUT22 = 0
    PutUpJointRad = 0
    GetDeg = 0
    GetUpDeg = 0
    currentPointA = 0
    currentJointDeg = 0
    msg_AGV_G011 = 0
    setPlanContext(sched.current_thread_id(), 1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    u8defu70b9_0_p={-0.23068754494035995,-0.17067611440899938,0.306303360248838,-3.0146975968405885,0.008741238129868436,-0.5220298672743885}
    u8defu70b9_0_q={0.23491831000700145,-0.5122448141556608,-2.2697247610068203,-0.10560252720069371,-1.668905072714902,-0.8093100381741527}
    u8defu70b9_1_p={-0.23059863914189563,-0.1706535265887313,0.39703410450966814,-3.014632367163287,0.008666003695316608,-0.5220284435290018}
    u8defu70b9_1_q={0.23491218652217846,-0.528713926587108,-2.03484931539358,0.1458407947724759,-1.6689014046868644,-0.8093100381741527}

    function str_cat(str1, str2)
      return tostring(str1) .. tostring(str2)
    end

    local function calculate_point_to_move_towards(feature, direction, position_distance)
      local posDir={direction[1], direction[2], direction[3]}
      if (math.norm(posDir) < 1e-6) then
          return getTargetTcpPose()
      end
      local direction_vector_normalized=math.normalize(posDir)
      local displacement_pose={direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,direction_vector_normalized[3] * position_distance,0,0,0}
    
      local wanted_displacement_in_base_frame=poseSub(poseTrans(feature, displacement_pose), feature)
      return poseAdd(getTargetTcpPose(), wanted_displacement_in_base_frame)
    end
    setPlanContext(sched.current_thread_id(), 2, "机器人编程")
    setPlanContext(sched.current_thread_id(), 3, "ARM 移动: LM1 向前, 路径: LM1->LM2")
    if (not agv.hasConnected()) then
        agv.disconnect()
        textmsg("AGV disconnected.")
    else
        textmsg("AGV connected.")
        local v = NaN
        local w = NaN
        local str = "LM1,LM2,LM1"
        local target_x = 0.21
        local target_y = -0.106
        local target_yaw = 3.1366
        local forward_flag = "forward"
        textmsg(setNavGoal)
        agv.setNavGoal(v, w, str, target_x, target_y, target_yaw, forward_flag)
        while true do
            if (agv.getNavStatus() == 1) then
                textmsg("Navigation has completed.")
                break
            else
                if (not agv.hasConnected()) then
                    agv.disconnect()
                    textmsg("AGV disconnected.")
                    sleep(0.5)
                    break
                end
                textmsg("Navigation is running...")
            end
        end
    end

    setPlanContext(sched.current_thread_id(), 4, "关节运动")
    setPlanContext(sched.current_thread_id(), 5, "路点_0")
    moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.3962634015954636, 1.0471975511965976, 0, 0)

    setPlanContext(sched.current_thread_id(), 6, "路点_1")
    moveJoint(inverseKinematics(u8defu70b9_1_q, u8defu70b9_1_p), 1.3962634015954636, 1.0471975511965976, 0, 0)

    setPlanContext(sched.current_thread_id(), 7, "路点_0")
    moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.3962634015954636, 1.0471975511965976, 0, 0)

    setPlanContext(sched.current_thread_id(), 8, "路点_1")
    moveJoint(inverseKinematics(u8defu70b9_1_q, u8defu70b9_1_p), 1.3962634015954636, 1.0471975511965976, 0, 0)

    setPlanContext(sched.current_thread_id(), 9, "路点_0")
    moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.3962634015954636, 1.0471975511965976, 0, 0)
end


function app:start(api)
  --
  self.api = api
  print("start---")
  p_Untitled_0()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app

