--- Auto generated by 'aubo_scope' v0.28.4-rc.18 2025-02-12 11:57:10
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_CE7()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(6)
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    setPayload(10, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    sleep(0)
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    setPlanContext(sched.current_thread_id(), 1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    u8defu70b9_1_p = {-1.04582990672275,-0.1325055295226656,0.6309217653935545,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_1_q = {3.459751776133433,-0.5385176625078112,1.021805923590762,-0.0104432316171711,1.570800644401703,0.2313753058110374}    
    u8defu70b9_2_p = {-1.072954683104939,-0.1040109968160503,0.6309217706966481,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_2_q = {3.426069735420582,-0.5834096881509018,0.9511736702143144,-0.0361990492930569,1.570795388278982,0.1977003654324953}    
    u8defu70b9_3_p = {-1.092554221932004,-0.0708660278806568,0.6309217758994168,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_3_q = {3.391277466636351,-0.6166054653736146,0.8977610558041639,-0.0564178092533623,1.57079547864453,0.1629081150143193}    
    u8defu70b9_4_p = {-1.104200401026355,-0.0341632023700202,0.63092178084797,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_4_q = {3.35576254857783,-0.6366949346776155,0.864952532017596,-0.0691407857010533,1.57079570068807,0.127393194745976}    
    u8defu70b9_5_p = {-1.107296948169465,0.0042183333438171,0.6309217852889472,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_5_q = {3.320594343506329,-0.6420113145990624,0.8562181007505185,-0.0725100541166651,1.570773296644978,0.09228259148277861}    
    u8defu70b9_6_p = {-1.101685323378413,0.0423134846778941,0.6309217889949745,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_6_q = {3.286818995411005,-0.6321141975166549,0.8724631352787678,-0.0662229670221893,1.570796453568711,0.0584495196273043}    
    u8defu70b9_7_p = {-1.087652835987569,0.0781718196307062,0.6309217917763078,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_7_q = {3.255510087991905,-0.6078397990536423,0.9119585460178155,-0.0510069237631961,1.570796781402677,0.0271405003824149}    
    u8defu70b9_8_p = {-1.065917934710483,0.1099574288656596,0.6309217934905454,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_8_q = {3.227775919081103,-0.5711174145093884,0.9706930862650786,-0.0289975899911206,1.570796987885392,-0.0005938081372374}    
    u8defu70b9_9_p = {-1.037593423815296,0.1360429223536218,0.6309217940499202,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_9_q = {3.204789095002469,-0.5243733399621907,1.043666275527506,-0.0027693734477277,1.570797099937711,-0.0235808063116669}    
    u8defu70b9_10_p = {-1.004129488707312,0.1550927500444583,0.6309217934257927,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_10_q = {3.187791021374116,-0.4701194586951207,1.125802936414615,0.0251138035540089,1.570797166823502,-0.0405790942215652}    
    u8defu70b9_11_p = {-0.9672394479492681,0.1661315806361419,0.6309217916501175,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_11_q = {3.17807451923672,-0.4107779310854247,1.212421098217116,0.0523915553733064,1.570797229826614,-0.0502958557111001}    
    u8defu70b9_12_p = {-0.9288120331385429,0.1685942375198048,0.6309217888138077,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_12_q = {3.176925659759026,-0.3487056842867847,1.299333122016612,0.0772327916931191,1.570797313772683,-0.0514450219508498}    
    u8defu70b9_13_p = {-0.8908146878199908,0.1623546352324335,0.630921785062079,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_13_q = {3.185501118738947,-0.2863222155255514,1.38277958761782,0.098297373653061,1.57079742936034,-0.0428699145891637}    
    u8defu70b9_14_p = {-0.8551928364291701,0.1477322349010143,0.6309217805870162,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_14_q = {3.204615404135079,-0.2262595566762058,1.459338345475595,0.1147950623031265,1.57079757566475,-0.023756014685391}    
    u8defu70b9_15_p = {-0.8237702805910352,0.1254756881661498,0.6309217756177377,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_15_q = {3.234427121118374,-0.1714630974032795,1.525882589905842,0.1265443659651044,1.570797739775158,0.0060553067408914}    
    u8defu70b9_16_p = {-0.7981558223795886,0.0967245069991724,0.6309217704086657,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_16_q = {3.274062704410502,-0.1251634686228574,1.579616305081706,0.1339798476667174,1.57079789491374,0.0456905243596944}    
    u8defu70b9_17_p = {-0.779660895330276,0.062950721878127,0.6309217652264988,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_17_q = {3.321306622526336,-0.0906392669586339,1.618183757396987,0.1380243416702855,1.570798001264937,0.0929341608583001}    
    u8defu70b9_18_p = {-0.7692324204112314,0.0258835153631391,0.6309217603365588,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_18_q = {3.372575493473625,-0.0707447545193664,1.639823002182285,0.1397701712914462,1.570798014928917,0.1442028908720779}    
    u8defu70b9_19_p = {-0.7674043246576997,-0.0125793102465057,0.6309217559892055,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_19_q = {3.423359124819596,-0.0673125031983868,1.643511892601411,0.1400214201286875,1.570841494586671,0.1949003060093467}    
    u8defu70b9_20_p = {-0.7742702046649096,-0.0504684984099971,0.6309217524070189,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_20_q = {3.46911639614926,-0.080664284027814,1.629091758408833,0.1389847173645619,1.570832686854418,0.2406668541092205}    
    u8defu70b9_21_p = {-0.78947853454005,-0.0858441622252693,0.6309217497734031,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_21_q = {3.506179938354423,-0.1095445934403927,1.597234420012182,0.1360418551566297,1.570820622854678,0.2777462510785241}    
    u8defu70b9_22_p = {-0.812250663661201,-0.1168951046143755,0.6309217482231966,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_22_q = {3.532358067355919,-0.1514541315349826,1.549387331199456,0.1300481722841382,1.570797011414021,0.3039865044611712}    
    u8defu70b9_23_p = {-0.8414206827767988,-0.1420315497241667,0.6309217478357682,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_23_q = {3.546961610405162,-0.2032011893130299,1.487729115294873,0.120138412516328,1.570796670005788,0.3185904974921422}    
    u8defu70b9_24_p = {-0.8754951173428303,-0.15996653779128,0.630921748630954,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_24_q = {3.55047143618558,-0.2614994296886858,1.414876915931325,0.1055860340514912,1.570796366275502,0.322100742264226}    
    u8defu70b9_25_p = {-0.9127293918612608,-0.1697818161392509,0.6309217505680412,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_25_q = {3.544070027576057,-0.3232740380908837,1.333832101109529,0.08631754270310089,1.570796106285065,0.3156997001892463}    
    u8defu70b9_26_p = {-0.9512171503253406,-0.1709748527574837,0.6309217535478531,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_26_q = {3.529258848363812,-0.3857725801457577,1.247895966327856,0.0628817376842853,1.57079588620031,0.3008888262484492}    
    u8defu70b9_27_p = {-0.9889878596581342,-0.1634845654158902,0.6309217574178262,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_27_q = {3.507607176314924,-0.4465062469980068,1.160681681145342,0.0364028743211485,1.57079569968329,0.2792373981681737}    
    u8defu70b9_28_p = {-1.024868782605751,-0.1473522606710938,0.6309217620786853,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_28_q = {3.480053103132828,-0.5043729149787172,1.074273025334093,0.0078627347797932,1.570795520153617,0.2516835335853387}    
    u8defu70b9_29_p = {-1.04582990672275,-0.1325055295226656,0.6309217653935545,-3.141592530787765,-3.894502375e-07,-1.48401832944856}    
    u8defu70b9_29_q = {3.459752210685997,-0.5385211360014421,1.021797063082872,-0.0104691619282507,1.570795860638157,0.2313823448026321}    
    
    
    function str_cat(str1, str2)
        return tostring(str1) .. tostring(str2)
    end
    
    local function calculate_point_to_move_towards(feature, direction, position_distance)
        local posDir={direction[1], direction[2], direction[3]}
        if (math.norm(posDir) < 1e-6) then
            return getTargetTcpPose()
        end
        local direction_vector_normalized=math.normalize(posDir)
        local displacement_pose={direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,direction_vector_normalized[3] * position_distance,0,0,0}

        local wanted_displacement_in_base_frame=poseSub(poseTrans(feature, displacement_pose), feature)
        return poseAdd(getTargetTcpPose(), wanted_displacement_in_base_frame)
    end
    setPlanContext(sched.current_thread_id(), 2, "机器人编程")
    setPlanContext(sched.current_thread_id(), 3, "Seeragv  Move To: LM4 default")
    function waitForMotionComplete()
      sleep(0)
    end
    waitForMotionComplete()
    agv.robot_task_gotarget_req("LM4",-2147483648,-2147483648,-2147483648,-2147483648,"")
    while true do
        if (agv.robot_status_task_req()=="COMPLETED") then
            print("Navigation has completed.")
            break
        else
            sleep(0.1)
            print("Navigation is running...")
        end
    end
    
    setPlanContext(sched.current_thread_id(), 4, "直线运动")
    setPlanContext(sched.current_thread_id(), 5, "路点_1")
    moveLine(u8defu70b9_1_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 6, "直线运动")
    setPlanContext(sched.current_thread_id(), 7, "路点_2")
    moveLine(u8defu70b9_2_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 8, "直线运动")
    setPlanContext(sched.current_thread_id(), 9, "路点_3")
    moveLine(u8defu70b9_3_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 10, "直线运动")
    setPlanContext(sched.current_thread_id(), 11, "路点_4")
    moveLine(u8defu70b9_4_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 12, "直线运动")
    setPlanContext(sched.current_thread_id(), 13, "路点_5")
    moveLine(u8defu70b9_5_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 14, "直线运动")
    setPlanContext(sched.current_thread_id(), 15, "路点_6")
    moveLine(u8defu70b9_6_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 16, "直线运动")
    setPlanContext(sched.current_thread_id(), 17, "路点_7")
    moveLine(u8defu70b9_7_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 18, "直线运动")
    setPlanContext(sched.current_thread_id(), 19, "路点_8")
    moveLine(u8defu70b9_8_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 20, "直线运动")
    setPlanContext(sched.current_thread_id(), 21, "路点_9")
    moveLine(u8defu70b9_9_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 22, "直线运动")
    setPlanContext(sched.current_thread_id(), 23, "路点_10")
    moveLine(u8defu70b9_10_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 24, "直线运动")
    setPlanContext(sched.current_thread_id(), 25, "路点_11")
    moveLine(u8defu70b9_11_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 26, "直线运动")
    setPlanContext(sched.current_thread_id(), 27, "路点_12")
    moveLine(u8defu70b9_12_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 28, "直线运动")
    setPlanContext(sched.current_thread_id(), 29, "路点_13")
    moveLine(u8defu70b9_13_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 30, "直线运动")
    setPlanContext(sched.current_thread_id(), 31, "路点_14")
    moveLine(u8defu70b9_14_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 32, "直线运动")
    setPlanContext(sched.current_thread_id(), 33, "路点_15")
    moveLine(u8defu70b9_15_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 34, "直线运动")
    setPlanContext(sched.current_thread_id(), 35, "路点_16")
    moveLine(u8defu70b9_16_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 36, "直线运动")
    setPlanContext(sched.current_thread_id(), 37, "路点_17")
    moveLine(u8defu70b9_17_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 38, "直线运动")
    setPlanContext(sched.current_thread_id(), 39, "路点_18")
    moveLine(u8defu70b9_18_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 40, "直线运动")
    setPlanContext(sched.current_thread_id(), 41, "路点_19")
    moveLine(u8defu70b9_19_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 42, "直线运动")
    setPlanContext(sched.current_thread_id(), 43, "路点_20")
    moveLine(u8defu70b9_20_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 44, "直线运动")
    setPlanContext(sched.current_thread_id(), 45, "路点_21")
    moveLine(u8defu70b9_21_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 46, "直线运动")
    setPlanContext(sched.current_thread_id(), 47, "路点_22")
    moveLine(u8defu70b9_22_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 48, "直线运动")
    setPlanContext(sched.current_thread_id(), 49, "路点_23")
    moveLine(u8defu70b9_23_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 50, "直线运动")
    setPlanContext(sched.current_thread_id(), 51, "路点_24")
    moveLine(u8defu70b9_24_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 52, "直线运动")
    setPlanContext(sched.current_thread_id(), 53, "路点_25")
    moveLine(u8defu70b9_25_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 54, "直线运动")
    setPlanContext(sched.current_thread_id(), 55, "路点_26")
    moveLine(u8defu70b9_26_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 56, "直线运动")
    setPlanContext(sched.current_thread_id(), 57, "路点_27")
    moveLine(u8defu70b9_27_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 58, "直线运动")
    setPlanContext(sched.current_thread_id(), 59, "路点_28")
    moveLine(u8defu70b9_28_p, 1.2, 0.1, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 60, "直线运动")
    setPlanContext(sched.current_thread_id(), 61, "路点_29")
    moveLine(u8defu70b9_29_p, 1.2, 0.1, 0, 0)
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_CE7()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


