--- Auto generated by 'aubo_scope' v0.28.4-rc.18 2024-12-20 13:54:57
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_cg()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(6)
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    setPayload(10, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    sleep(0)
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    setPlanContext(sched.current_thread_id(), 1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    u8defu70b9_0_p = {-0.7276992671355346,-0.7831372793935263,0.4995093210263517,-2.735457137596557,0.03706726164107513,2.877047481842415}    
    u8defu70b9_0_q = {-2.143953650901441,-0.9231601009448318,0.5310509077931843,-2.876663877481452,-1.723775893773345,-0.2693798517146415}    
    u8defu70b9_1_p = {-0.202016136350947,-0.3136254041706862,0.3516590557354244,0.006691453941646084,-0.1103444072576608,-2.41080935358037}    
    u8defu70b9_1_q = {-1.597551381804197,-0.0199427627710862,2.761711960476707,1.293135341392343,-1.645735591529545,0.7563601939658687}    
    u8defu70b9_2_p = {-0.7034327388715412,-0.8027740553843909,-0.03841534849269812,-2.735412503480652,0.03703200978702176,2.877062227227896}    
    u8defu70b9_2_q = {-2.113843751220725,-1.189553668388579,0.9398419973163396,-2.197209953757778,-1.711487847013094,-0.2404903864737484}    
    u8defu70b9_3_p = {-0.5991675204706747,-0.2155356751715027,-0.03812345265522093,-2.656944671043867,0.2087399281736737,-2.246153704078717}    
    u8defu70b9_3_q = {-2.536440776618913,-0.9056271561771566,1.841436176875745,-2.304331426652266,-1.976060213063787,-1.874606200101131}    
    u8defu70b9_4_p = {-0.7494376475568469,-0.7655249503631435,-0.03839422754696848,-2.655633695749821,0.2142098947933381,2.886685021194028}    
    u8defu70b9_4_q = {-2.187520730334539,-1.202836693226429,0.9165919759274275,-2.185293167474243,-1.917773668257473,-0.2331124282728287}    
    u8defu70b9_5_p = {-0.599168328595291,-0.2155417076302449,0.4155454427426828,-2.656930440447086,0.2087417687931096,-2.246124741667459}    
    u8defu70b9_5_q = {-2.536713484314537,-0.3555446832270844,1.75385869227606,-2.942530886203259,-1.978174372723923,-1.875971088617349}    
    u8defu70b9_6_p = {-0.5366894466100564,-0.1739891175698747,0.3943478128108569,-2.725914750107914,-0.04777874115884726,-2.250865010060325}    
    u8defu70b9_6_q = {-2.53500703615974,-0.2218261097806623,1.916620110911488,-2.647933672871969,-1.984138841037127,-1.875764532788485}    
    u8defu70b9_7_p = {-0.5366986477298955,-0.1739859133630332,0.5343399074243161,-2.725897853808408,-0.04777350643736766,-2.250876109239838}    
    u8defu70b9_7_q = {-2.53526759351249,-0.1246841185003004,1.774387271165253,-2.887663987897023,-1.984618104561615,-1.876629907208758}    
    u8defu70b9_8_p = {-0.5735135604118746,0.1094475955155723,0.428112024593119,-3.129069843516026,-0.05918398041401029,-1.626815319010287}    
    u8defu70b9_8_q = {-2.989822720746391,-0.1870288778266448,1.86518766489504,-2.65817641191504,-1.633157286578407,-2.929768976070908}    
    u8defu70b9_9_p = {-0.5735507707132679,0.1094364085014383,-0.1072028044803006,-3.129138496736782,-0.05924806049456587,-1.626824485627795}    
    u8defu70b9_9_q = {-2.989516262098338,-0.8950131566573706,1.999847795076837,-1.815420529922115,-1.629953646173872,-2.929129058012859}    
    u8defu70b9_11_p = {-0.6777254968297934,0.1360977238812094,-0.02230850656607712,0.09267287256965448,-0.5386355582304396,1.05379386706067}    
    u8defu70b9_11_q = {-3.114582441380132,-0.9906620058022857,2.127584305085433,1.333938892840576,-2.07826889732275,-0.5773356920172208}    
    u8defu70b9_12_p = {-0.2020161518807609,-0.3136260593589628,0.3516592727460453,0.00669143776102914,-0.1103442476858899,-2.410810694822482}    
    u8defu70b9_12_q = {-1.597551381804197,-0.0199427627710862,2.761710833585402,1.293133991354245,-1.645735591529545,0.7563588439277716}    
    u8defu70b9_17_p = {}    
    u8defu70b9_17_q = {}    
    u8defu70b9_18_p = {}    
    u8defu70b9_18_q = {}    
    u8defu70b9_19_p = {}    
    u8defu70b9_19_q = {}    
    u8defu70b9_21_p = {-0.6826376056993342,-0.8151930849305727,0.4587517981355049,-2.878216883831544,-0.1403827142161485,2.909103105970825}    
    u8defu70b9_21_q = {-2.072281478361893,-0.9157834927820092,0.6213329315230253,-2.882084280441505,-1.509747604041815,-0.2946093636741635}    
    u8defu70b9_22_p = {-0.6826383456157529,-0.8151963379727983,-0.08350912751908868,-2.940975729017883,0.125841356053159,2.909564786378406}    
    u8defu70b9_22_q = {-2.093666081820735,-1.293485001259504,0.8326757611751924,-2.425244888747229,-1.746016421385779,-0.2613309245794387}    
    u8defu70b9_23_p = {-0.682638583418087,-0.8152082382388577,-0.08018633521998711,-2.878194514186699,-0.140383036101344,2.909087948306175}    
    u8defu70b9_23_q = {-2.072508284762215,-1.244250461894574,0.9127932253408618,-2.262152186383037,-1.508801227335714,-0.2943704069309681}    
    u8defu70b9_24_p = {-0.4769585641945835,0.01431553571627259,-0.08343742216125059,-3.136923747323627,0.05660752829495562,-1.917283539732872}    
    u8defu70b9_24_q = {-2.728674051310067,-0.8248678772056988,2.215139251859032,-1.713169994482141,-1.53153316881551,-2.376432911306706}    
    u8defu70b9_25_p = {-0.4990265530005605,0.01307769777500319,-0.0834309859447491,-2.940743322753873,0.1254754067593442,-1.899365635373432}    
    u8defu70b9_25_q = {-2.761195119032291,-0.8747139838286371,2.129727652346082,-1.939525482078739,-1.607017848941406,-2.419248019519693}    
    u8defu70b9_26_p = {-0.4769530349343855,0.01432026887731145,0.3927132383833808,-3.136905223596435,0.05662332754457248,-1.917268602272994}    
    u8defu70b9_26_q = {-2.729143864567875,-0.05343990803754915,2.095729341697406,-2.60398858277167,-1.535225523011213,-2.37734553706038}    
    u8defu70b9_10_p = {-0.8048489805253335,-0.1503455853212625,0.7158770380162184,-1.565841283168415,0.8119034968393836,1.583850500094215}    
    u8defu70b9_10_q = {-2.654998422234351,-0.1514702243858352,1.396122540182435,-1.5895470059262,-1.091034638249125,0.8122423209211606}    
    u8defu70b9_13_p = {-0.8048534915508869,0.009036304688169704,0.715894796128846,-1.56586345945769,0.8118944571833002,1.583837124447284}    
    u8defu70b9_13_q = {-2.869904236729027,-0.1261489098357071,1.425198589614226,-1.585629195368274,-1.305924252286636,0.8133561023513086}    
    u8defu70b9_14_p = {-0.9940793449610843,-0.1503438118113982,0.7158799303144188,-1.565851387338432,0.8118932273834015,1.583846492415117}    
    u8defu70b9_14_q = {-2.755506058490905,-0.4716061084008936,0.9700595876393173,-1.695080834018441,-1.19208228974454,0.8118251591491416}    
    u8defu70b9_15_p = {-0.9940758441381552,-0.4052914814513345,0.715886281795109,-1.565835205420353,0.8119012201737847,1.583871332218939}    
    u8defu70b9_15_q = {-2.514537758530766,-0.6257818091334155,0.7277351353599032,-1.782730707437748,-0.9515689526231398,0.8099877572989216}    
    u8defu70b9_16_p = {-0.701007805305002,-0.4053091339968695,0.7158911367565928,-1.5658197497394,0.8119170075860219,1.583908979491975}    
    u8defu70b9_16_q = {-2.275821322116672,-0.1565004663358127,1.390237913791736,-1.589988468383968,-0.7119061395029438,0.8099877572989216}    
    u8defu70b9_20_p = {-0.6662049839611183,-0.2908914401675355,0.7158980697346383,-1.565828015064424,0.8119281668705333,1.583909789558104}    
    u8defu70b9_20_q = {-2.355053708000254,-0.01384869080055525,1.545977672710494,-1.577480365413882,-0.7910777736721545,0.8111001886909724}    
    u8defu70b9_27_p = {-0.2020168804860459,-0.3136280410341913,0.3516598625877395,0.006689662412949215,-0.1103390784045147,-2.410810294354697}    
    u8defu70b9_27_q = {-1.597552731842294,-0.01994141273298905,2.76170745291149,1.293124541087565,-1.64573289145335,0.7563601939658687}    
    u8defu70b9_28_p = {-0.7856055019265673,-0.79678357537849,-0.08014415197037744,-2.876705594432859,0.00268503402025641,2.966256951869045}    
    u8defu70b9_28_q = {-2.178081263959272,-1.375258158841921,0.6326491740001218,-2.461992925751626,-1.682371575371879,-0.4158657354458024}    
    u8defu70b9_29_p = {-0.7856031877458507,-0.7967876650054866,-0.08013812143181799,-2.902219506315173,0.145696025658189,2.964365677759331}    
    u8defu70b9_29_q = {-2.187948692411335,-1.412663664399631,0.5670088824199192,-2.571131355563255,-1.800967022054037,-0.4015850324541594}    
    u8defu70b9_30_p = {-0.6826436038373072,-0.1276343894895892,-0.08349124719861939,-2.940959439256413,0.1258397763552384,2.909563874998493}    
    u8defu70b9_30_q = {-2.696427041321564,-0.9218141129619742,1.782970802229587,-1.974887029957365,-1.804230064134847,-0.8724945211969239}    
    u8defu70b9_31_p = {-0.626718803177824,-0.2201081249244726,-0.0435889916884566,-2.677607000056319,0.1903815714791848,2.946252481488846}    
    u8defu70b9_31_q = {-2.561452932444794,-0.8194744750075882,1.887771693523151,-1.785309280203302,-2.022531224443853,-0.6945716503355497}    
    u8defu70b9_32_p = {-0.5647701817143749,-0.7655336020445672,-0.03837269515589148,-2.655613269047973,0.214242137466087,2.886702308506794}    
    u8defu70b9_32_q = {-2.021837304861918,-1.020975761235671,1.31112789045205,-1.9236800849325,-1.848106302292192,-0.0742507453051022}    
    u8defu70b9_33_p = {-0.5735312181800822,0.1094403970107324,-0.1071759593026544,-2.810063449146715,-0.03867999636418726,-1.642577532474816}    
    u8defu70b9_33_q = {-2.997245230204517,-0.9651867869090826,1.932334610149001,-2.129679698100284,-1.676332854963331,-2.943907925062351}    
    u8defu70b9_34_p = {-0.5735457003099336,0.1094386830871084,-0.1071721121759015,-2.81005462844159,-0.0387351625232019,-1.910813873814863}    
    u8defu70b9_34_q = {-3.009997690070187,-0.9595341773963193,1.934343857344446,-2.097435388187975,-1.751983589775177,-2.697123660979693}    
    u8defu70b9_35_p = {-0.5913870438666747,-0.4950520717356686,-0.08241392432334403,-2.940872775143628,0.1258339448877988,2.90955882070121}    
    u8defu70b9_35_q = {-2.205661192245931,-0.954467484417719,1.646825429308813,-1.970309050769932,-1.761979271846469,-0.3723081062793844}    
    u8defu70b9_36_p = {-0.5825445748534422,0.1087693208627032,0.1905433898540093,-3.136860528364524,0.05647868698514628,-1.681351507355129}    
    u8defu70b9_36_q = {-2.971652557996861,-0.447503878252491,2.010183642119252,-2.273376403122735,-1.518478300416078,-2.855662684842201}    
    u8defu70b9_37_p = {-0.5825395606387864,0.1087762690566246,0.5852282016225471,-3.136870382052551,0.05646193715125206,-1.681347900539488}    
    u8defu70b9_37_q = {-2.972224974150052,-0.1142901751903496,1.674663025197253,-2.942000321231079,-1.520199598989943,-2.857451485320924}    
    
    
    function str_cat(str1, str2)
        return tostring(str1) .. tostring(str2)
    end
    
    local function calculate_point_to_move_towards(feature, direction, position_distance)
        local posDir={direction[1], direction[2], direction[3]}
        if (math.norm(posDir) < 1e-6) then
            return getTargetTcpPose()
        end
        local direction_vector_normalized=math.normalize(posDir)
        local displacement_pose={direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,direction_vector_normalized[3] * position_distance,0,0,0}

        local wanted_displacement_in_base_frame=poseSub(poseTrans(feature, displacement_pose), feature)
        return poseAdd(getTargetTcpPose(), wanted_displacement_in_base_frame)
    end
    setPlanContext(sched.current_thread_id(), 2, "机器人编程")
    while true do
        setPlanContext(sched.current_thread_id(), 3, "Seeragv  Move To: LM1 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM1",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        
        setPlanContext(sched.current_thread_id(), 4, "Seeragv  Move To: LM2 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM2",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        
        setPlanContext(sched.current_thread_id(), 5, "关节运动")
        setPlanContext(sched.current_thread_id(), 6, "路点_1")
        moveJoint(inverseKinematics(u8defu70b9_1_q, u8defu70b9_1_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 7, "路点_0")
        moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 8, "路点_2")
        moveJoint(inverseKinematics(u8defu70b9_2_q, u8defu70b9_2_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 9, "路点_4")
        moveJoint(inverseKinematics(u8defu70b9_4_q, u8defu70b9_4_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 10, "直线运动")
        setPlanContext(sched.current_thread_id(), 11, "路点_32")
        moveLine(u8defu70b9_32_p, 1.2, 0.25, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 12, "路点_31")
        moveLine(u8defu70b9_31_p, 1.2, 0.25, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 13, "路点_3")
        moveJoint(inverseKinematics(u8defu70b9_3_q, u8defu70b9_3_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 14, "路点_5")
        moveJoint(inverseKinematics(u8defu70b9_5_q, u8defu70b9_5_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 15, "路点_6")
        moveJoint(inverseKinematics(u8defu70b9_6_q, u8defu70b9_6_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 16, "路点_7")
        moveJoint(inverseKinematics(u8defu70b9_7_q, u8defu70b9_7_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 17, "路点_8")
        moveJoint(inverseKinematics(u8defu70b9_8_q, u8defu70b9_8_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 18, "路点_9")
        moveJoint(inverseKinematics(u8defu70b9_9_q, u8defu70b9_9_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 19, "路点_33")
        moveJoint(inverseKinematics(u8defu70b9_33_q, u8defu70b9_33_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 20, "路点_34")
        moveJoint(inverseKinematics(u8defu70b9_34_q, u8defu70b9_34_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 21, "路点_11")
        moveJoint(inverseKinematics(u8defu70b9_11_q, u8defu70b9_11_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 22, "路点_12")
        moveJoint(inverseKinematics(u8defu70b9_12_q, u8defu70b9_12_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 23, "Seeragv  Move To: LM3 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM3",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        
        setPlanContext(sched.current_thread_id(), 24, "Seeragv  Move To: LM4 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM4",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        
        setPlanContext(sched.current_thread_id(), 25, "关节运动")
        setPlanContext(sched.current_thread_id(), 26, "路点_21")
        moveJoint(inverseKinematics(u8defu70b9_21_q, u8defu70b9_21_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 27, "路点_23")
        moveJoint(inverseKinematics(u8defu70b9_23_q, u8defu70b9_23_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 28, "路点_28")
        moveJoint(inverseKinematics(u8defu70b9_28_q, u8defu70b9_28_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 29, "路点_29")
        moveJoint(inverseKinematics(u8defu70b9_29_q, u8defu70b9_29_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 30, "路点_22")
        moveJoint(inverseKinematics(u8defu70b9_22_q, u8defu70b9_22_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 31, "直线运动")
        setPlanContext(sched.current_thread_id(), 32, "路点_35")
        moveLine(u8defu70b9_35_p, 1.2, 0.25, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 33, "路点_30")
        moveJoint(inverseKinematics(u8defu70b9_30_q, u8defu70b9_30_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 34, "路点_25")
        moveJoint(inverseKinematics(u8defu70b9_25_q, u8defu70b9_25_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 35, "路点_24")
        moveJoint(inverseKinematics(u8defu70b9_24_q, u8defu70b9_24_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 36, "路点_26")
        moveJoint(inverseKinematics(u8defu70b9_26_q, u8defu70b9_26_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 37, "路点_36")
        moveJoint(inverseKinematics(u8defu70b9_36_q, u8defu70b9_36_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 38, "路点_37")
        moveJoint(inverseKinematics(u8defu70b9_37_q, u8defu70b9_37_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 39, "关节运动")
        setPlanContext(sched.current_thread_id(), 40, "路点_13")
        moveJoint(inverseKinematics(u8defu70b9_13_q, u8defu70b9_13_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 41, "路点_10")
        moveJoint(inverseKinematics(u8defu70b9_10_q, u8defu70b9_10_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 42, "路点_14")
        moveJoint(inverseKinematics(u8defu70b9_14_q, u8defu70b9_14_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 43, "路点_15")
        moveJoint(inverseKinematics(u8defu70b9_15_q, u8defu70b9_15_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 44, "路点_16")
        moveJoint(inverseKinematics(u8defu70b9_16_q, u8defu70b9_16_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 45, "路点_20")
        moveJoint(inverseKinematics(u8defu70b9_20_q, u8defu70b9_20_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 46, "路点_27")
        moveJoint(inverseKinematics(u8defu70b9_27_q, u8defu70b9_27_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 47, "Seeragv  Move To: LM3 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM3",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        
        setPlanContext(sched.current_thread_id(), 48, "Seeragv  Move To: LM2 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM2",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        
        setPlanContext(sched.current_thread_id(), 49, "Seeragv  Move To: LM1 ")
        function waitForMotionComplete()
          sleep(0)
        end
        waitForMotionComplete()
        agv.robot_task_gotarget_req("LM1",-2147483648,-2147483648,-2147483648,-2147483648,"")
        while true do
            if (agv.robot_status_task_req()=="COMPLETED") then
                print("Navigation has completed.")
                break
            else
                sleep(0.1)
                print("Navigation is running...")
            end
        end
        sched.cancel_point()
    end
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_cg()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


