--- Auto generated by 'aubo_scope' v0.28.4-rc.18 2024-10-25 09:24:39
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_Untitled_2()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(6)
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    setPayload(10, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    sleep(0)
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    setPlanContext(sched.current_thread_id(), 1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    u8defu70b9_0_p = {0.04671447256615448,-0.9972909214080335,0.5651349666474039,0.628931110904272,-0.4893240164413948,0.6168493544395334}    
    u8defu70b9_0_q = {-1.307615850022364,-0.4230519882369269,1.462239506784327,-0.4473108228045987,-1.41408930463022,-2.565380193269401}    
    u8defu70b9_1_p = {-0.3579090525573105,-1.047881353133126,0.5193883335497811,0.6056538804195342,-0.4821435139859459,0.2300240978072331}    
    u8defu70b9_1_q = {-1.70502116452775,-0.613977076011944,1.249522996632301,-0.4473067726903073,-1.41407985436354,-2.565377493193206}    
    u8defu70b9_2_p = {-0.4859546054257565,-0.9210926004794759,0.5845020805477691,0.687168766698053,-0.5073272385042471,0.04741146893065495}    
    u8defu70b9_2_q = {-1.848892024464732,-0.4784197506772049,1.333211579341082,-0.5751999317475309,-1.414078504325443,-2.565366692888429}    
    u8defu70b9_3_p = {-0.3206419857629365,-0.9440040731178546,0.5837762759558015,0.7178019978518159,-0.5158718955701178,0.1999052206347531}    
    u8defu70b9_3_q = {-1.681508901027801,-0.4086025304831403,1.431078708439707,-0.5751945315951423,-1.414075804249249,-2.565366692888429}    
    u8defu70b9_4_p = {-0.006857316462947701,-1.005688969136056,0.5624326955410532,0.7417878106043339,-0.5224209286173975,0.506708260444342}    
    u8defu70b9_4_q = {-1.362802707357624,-0.4304299464378466,1.43108208911362,-0.5751945315951423,-1.414075804249249,-2.565366692888429}    
    u8defu70b9_5_p = {-0.01979587899925455,-0.582390672587178,0.6858535056192071,1.226496239970039,-0.5903810562922491,0.3808991460215546}    
    u8defu70b9_5_q = {-1.227323684232519,0.2751202137037194,1.895002955022407,-1.232690085668687,-1.414066353982568,-2.565363992812235}    
    u8defu70b9_6_p = {-0.252536992961589,-0.5251633754029382,0.6858527801918496,1.226498191381636,-0.590379451629319,-0.03335346486842798}    
    u8defu70b9_6_q = {-1.641576124152229,0.2751188636656222,1.895002955022407,-1.232690085668687,-1.414067704020666,-2.565365342850332}    
    u8defu70b9_7_p = {-0.2706695040006296,-0.7832374666452038,0.671977707204755,1.280757091448686,-0.5923715850092409,-0.06354297507200078}    
    u8defu70b9_7_q = {-1.641574774114131,-0.136127041411736,1.528861320690516,-1.23266038483055,-1.414067704020666,-2.565365342850332}    
    u8defu70b9_8_p = {-0.4297283152167556,-0.688554201137381,0.6946250198481115,1.246814710934357,-0.5918786611492793,-0.2641605572875484}    
    u8defu70b9_8_q = {-1.861171970996401,-0.1032927648509732,1.533528904472644,-1.232659034792452,-1.4140987548969,-2.565366692888429}    
    u8defu70b9_9_p = {-0.5894669775120388,-0.7500132389107956,0.6795170281083821,1.3675461232116,-0.5914702636969488,-0.4807601956109196}    
    u8defu70b9_9_q = {-2.009880017435469,-0.3467235343003123,1.23780332706829,-1.385143137789247,-1.414087954592123,-2.565365342850332}    
    
    
    function str_cat(str1, str2)
        return tostring(str1) .. tostring(str2)
    end
    
    local function calculate_point_to_move_towards(feature, direction, position_distance)
        local posDir={direction[1], direction[2], direction[3]}
        if (math.norm(posDir) < 1e-6) then
            return getTargetTcpPose()
        end
        local direction_vector_normalized=math.normalize(posDir)
        local displacement_pose={direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,direction_vector_normalized[3] * position_distance,0,0,0}

        local wanted_displacement_in_base_frame=poseSub(poseTrans(feature, displacement_pose), feature)
        return poseAdd(getTargetTcpPose(), wanted_displacement_in_base_frame)
    end
    setPlanContext(sched.current_thread_id(), 2, "机器人编程")
    while true do
        setPlanContext(sched.current_thread_id(), 3, "关节运动")
        setPlanContext(sched.current_thread_id(), 4, "路点_0")
        moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 5, "关节运动")
        setPlanContext(sched.current_thread_id(), 6, "路点_1")
        moveJoint(inverseKinematics(u8defu70b9_1_q, u8defu70b9_1_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 7, "关节运动")
        setPlanContext(sched.current_thread_id(), 8, "路点_2")
        moveJoint(inverseKinematics(u8defu70b9_2_q, u8defu70b9_2_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 9, "关节运动")
        setPlanContext(sched.current_thread_id(), 10, "路点_3")
        moveJoint(inverseKinematics(u8defu70b9_3_q, u8defu70b9_3_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 11, "关节运动")
        setPlanContext(sched.current_thread_id(), 12, "路点_4")
        moveJoint(inverseKinematics(u8defu70b9_4_q, u8defu70b9_4_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 13, "关节运动")
        setPlanContext(sched.current_thread_id(), 14, "路点_5")
        moveJoint(inverseKinematics(u8defu70b9_5_q, u8defu70b9_5_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 15, "关节运动")
        setPlanContext(sched.current_thread_id(), 16, "路点_6")
        moveJoint(inverseKinematics(u8defu70b9_6_q, u8defu70b9_6_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 17, "关节运动")
        setPlanContext(sched.current_thread_id(), 18, "路点_7")
        moveJoint(inverseKinematics(u8defu70b9_7_q, u8defu70b9_7_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 19, "关节运动")
        setPlanContext(sched.current_thread_id(), 20, "路点_8")
        moveJoint(inverseKinematics(u8defu70b9_8_q, u8defu70b9_8_p), 1.39626, 1.0472, 0, 0)
        
        setPlanContext(sched.current_thread_id(), 21, "关节运动")
        setPlanContext(sched.current_thread_id(), 22, "路点_9")
        moveJoint(inverseKinematics(u8defu70b9_9_q, u8defu70b9_9_p), 1.39626, 1.0472, 0, 0)
        sched.cancel_point()
    end
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_Untitled_2()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


