--- Auto generated by 'aubo_scope' v0.28.4-rc.18 2025-02-12 09:40:40
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_zx()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(6)
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    setPayload(10, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    local agv =sched.jsonrpc.proxy('http://127.0.0.1:8989/jsonrpc')
    sleep(0)
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(0)
    setToolIoInput(0, true)
    setToolIoInput(1, true)
    setToolIoInput(2, true)
    setToolIoInput(3, true)
    setPlanContext(sched.current_thread_id(), 1, "初始变量")
    u57fau5ea7 = {0,0,0,0,0,0}
    u5de5u5177 = {0,0,0,0,0,0}
    u8defu70b9_0_p = {-0.2020274519450942,-0.3137065379109122,0.3517867103714448,0.006997600561195074,-0.1105973790661363,-2.410886966823251}    
    u8defu70b9_0_q = {-1.597574332451849,-0.01977535804703971,2.761461790607167,1.293111040706594,-1.645712640881893,0.7563372433182172}    
    u8defu70b9_1_p = {-0.6089787686204343,-0.3821810959233956,0.5027045434789832,-0.1458300284620781,0.1841706372492264,2.451197570937676}    
    u8defu70b9_1_q = {-2.274873595372473,-0.1599835646264573,2.089606941241514,0.5304731695889819,-1.388354878422364,0.03688574089030714}    
    u8defu70b9_3_p = {-0.6090049224904547,0.5586430631035065,0.3210268486868087,-0.1458661618776738,0.1842127332155967,2.451323478902761}    
    u8defu70b9_3_q = {-3.652606374046468,-0.5166595797789525,1.971629309927566,0.7118872389695837,-1.680516623026396,1.38989122177692}    
    u8defu70b9_4_p = {-0.6090170692105995,-0.4263745966977811,0.3210287378993747,-0.1458633937332102,0.1842705680995167,2.451342957469856}    
    u8defu70b9_4_q = {-2.234124045448125,-0.4373893928286501,2.138270615323464,0.8640716335088109,-1.383609494510885,-0.004499676977797881}    
    u8defu70b9_5_p = {-0.553645783762904,-0.4263811197628628,0.154976445993835,-0.1458636141616633,0.1843531735296315,2.451340317161489}    
    u8defu70b9_5_q = {-2.167680570458836,-0.694836257802591,2.219570188467272,1.215608053625459,-1.375881876442804,-0.07170322341578189}    
    u8defu70b9_6_p = {-0.862457656921112,-0.2719736700257082,0.5522359901033813,-0.253876359060662,0.3645642799517341,2.263783073400787}    
    u8defu70b9_6_q = {-2.580258963138081,-0.3408414183110337,1.7068695786722,0.1650408073383778,-1.253939685317813,0.2255778656526396}    
    u8defu70b9_7_p = {-0.9805485412486494,-0.2372164430075019,1.050849064560536,-0.2710158300532166,0.3851838010131881,2.444381410652301}    
    u8defu70b9_7_q = {-2.682590500863884,-0.5250203657145968,0.5529959890517958,-0.903511646478924,-1.344010177045309,0.5144941186711255}    
    u8defu70b9_8_p = {-0.9805464568105285,-0.4219995009633117,1.050845736823244,-0.2710164450087623,0.3852004511864411,2.444395943341346}    
    u8defu70b9_8_q = {-2.519921710462197,-0.7352955495360516,0.1913562854803106,-1.015413604275417,-1.282487590920128,0.3593760913467934}    
    u8defu70b9_9_p = {-0.980545255577314,-0.2372136346936077,1.050850893735357,-0.2710091261892096,0.3851800745762932,2.444387298298561}    
    u8defu70b9_9_q = {-2.68259185090198,-0.5250122654860139,0.5530072579648382,-0.9035021962122439,-1.344012877121503,0.514498168785417}    
    u8defu70b9_10_p = {-0.9805385891477011,0.277451481117757,1.050859046154788,-0.2709983386436212,0.3851776709381757,2.444383427404801}    
    u8defu70b9_10_q = {-3.219649156290759,-0.5647965381709001,0.4781895636029712,-0.9929962216722565,-1.577484415528173,1.002865000162416}    
    u8defu70b9_11_p = {-0.9805382217703871,0.424500684628914,1.006718686353463,-0.2710004030559303,0.3851789235271177,2.44437254759916}    
    u8defu70b9_11_q = {-3.367578230747772,-0.646931505963353,0.4235432235868548,-0.960064742368499,-1.643977841927057,1.135319937949907}    
    u8defu70b9_12_p = {-0.9805262183764153,0.6632212459729108,0.8948229919871948,-0.2709888974206916,0.3852042893995211,2.444325552148778}    
    u8defu70b9_12_q = {-3.578579735065493,-0.9260478324346336,0.1184475449878125,-0.9629659742392724,-1.736778110686987,1.32703749808795}    
    u8defu70b9_13_p = {-0.9035663671375205,0.7348216303353863,0.6931053124472887,-0.2709729578521324,0.385217275385703,2.444311596761036}    
    u8defu70b9_13_q = {-3.668049459839756,-0.703259145490704,0.8785762977791652,-0.4106667387336813,-1.772739075480747,1.408477196260371}    
    u8defu70b9_14_p = {-0.8081441399629891,0.7348018806828931,0.5437075514812952,-0.2709385104886978,0.3852090844946756,2.444365282305239}    
    u8defu70b9_14_q = {-3.714693276096257,-0.6215048884416472,1.270627416977956,-0.09132602715784376,-1.791299399240353,1.451303104778134}    
    u8defu70b9_15_p = {-0.8081484121958805,-0.4485434751268957,0.5437094227176338,-0.2709325585914067,0.3852356727496573,2.444387328774066}    
    u8defu70b9_15_q = {-2.382595835220192,-0.3718625937073253,1.6736105087191,0.1460376710829073,-1.232934442564271,0.2209701856270698}    
    u8defu70b9_16_p = {-0.8081527100110589,-0.4485506007683189,0.309798066544163,-0.2709199658823023,0.3852588880190692,2.444405924028109}    
    u8defu70b9_16_q = {-2.382610685639261,-0.5941139654885896,1.803485858423128,0.49842461520076,-1.233797116908349,0.2202060640640834}    
    u8defu70b9_17_p = {-0.8081569983884356,0.7922987987958028,0.3098033033837782,-0.2709058056501606,0.3852753867670152,2.444414935183748}    
    u8defu70b9_17_q = {-3.75957934275027,-0.8450941479771863,1.303209225257212,0.1743574202468036,-1.809767920409352,1.493197487008865}    
    u8defu70b9_18_p = {-0.7703035835823792,0.7922975687460337,0.3098045330358346,-0.2708983507329912,0.3852753704181238,2.444422887806536}    
    u8defu70b9_18_q = {-3.780440131427418,-0.8104845713186725,1.371961990619703,0.2132425675589885,-1.817870849068441,1.51286619204623}    
    u8defu70b9_19_p = {-0.787525767117802,0.811446501960648,0.0638296509032846,-0.2262290288894559,0.3163752824586253,2.400039690463121}    
    u8defu70b9_19_q = {-3.780414480703571,-1.111719921973644,1.282729102694102,0.4878430165953055,-1.763562866534425,1.468964303165039}    
    u8defu70b9_20_p = {-0.7875328521852732,-0.5681453456786641,0.06383564253055142,-0.2262107553511949,0.3163986063095335,2.400038017607508}    
    u8defu70b9_20_q = {-2.27860645071109,-0.9759627910005264,1.66714778708933,0.8483031885341097,-1.255007565452658,0.0346014764299309}    
    u8defu70b9_21_p = {-0.5536747093459,0.4448431574688202,0.1549631227985262,-0.1456904584092845,0.1844626023088991,2.451246149633918}    
    u8defu70b9_21_q = {-3.545078539684738,-0.6846475202834068,2.198091640208613,1.095670669074735,-1.658749958786062,1.283724225817116}    
    u8defu70b9_22_p = {-0.6346696583959044,0.4797952148431901,-0.05919767412186595,-0.07394563438328595,-0.0456948027987124,2.455292059171197}    
    u8defu70b9_22_q = {-3.545146041589596,-1.132370104707636,1.867196912090486,1.453503666876488,-1.656619598668761,1.284280441513142}    
    u8defu70b9_23_p = {-0.6580897887130205,-0.2362574655051877,-0.1286862265855809,-0.04274727033166555,0.1778833551970212,2.623273839802819}    
    u8defu70b9_23_q = {-2.486261210585978,-1.218032722047939,2.014699095575309,1.555042732239264,-1.426046592056669,0.4054015901547998}    
    u8defu70b9_24_p = {-0.658098382003925,-0.3782839466648612,-0.1286880556105688,-0.04273133817895471,0.1778930250790833,2.623254308713935}    
    u8defu70b9_24_q = {-2.332633625320899,-1.218062422886077,1.907487783781992,1.471781832673789,-1.410900514644754,0.2506669736500581}    
    u8defu70b9_25_p = {-0.6089794365645953,-0.382180453525044,0.5027053542220054,-0.1458275090554899,0.1841706121563513,2.45119668416303}    
    u8defu70b9_25_q = {-2.27487494541057,-0.1599835646264573,2.08960581435021,0.530474519627079,-1.388354878422364,0.03688574089030714}    
    u8defu70b9_26_p = {-0.2020300703737184,-0.3137102667082944,0.3517886032383513,0.007001091845123206,-0.1105940855194221,-2.410903168745284}    
    u8defu70b9_26_q = {-1.597581082642334,-0.01977535804703971,2.761452775476733,1.293101590439914,-1.645708590767602,0.7563277930515372}    
    u8defu70b9_27_p = {-0.6089889882036347,-0.3821883437188412,0.4361883369605903,-0.1458369157661843,0.184298638836349,2.451257380892591}    
    u8defu70b9_27_q = {-2.274833094229558,-0.2409858504554021,2.135525508106355,0.6574253520924928,-1.38863163623228,0.03666433464237469}    
    u8defu70b9_28_p = {-0.6090002557034533,0.6149394102412112,0.4111427630351056,-0.145781260324315,0.1843513153129531,2.451246098043035}    
    u8defu70b9_28_q = {-3.712549415597985,-0.4535439486991361,1.860615866873772,0.5445176159136238,-1.692122900547587,1.449249696832371}    
    u8defu70b9_2_p = {-0.7875342900307623,-0.5681388567478273,0.5155315084486632,-0.2261740870278192,0.3164055101977263,2.400062439225454}    
    u8defu70b9_2_q = {-2.278609150787284,-0.4765256472269048,1.594749528357649,0.276312297343502,-1.253063510592764,0.03522249395461947}    
    u8defu70b9_29_p = {-0.2020319720965331,-0.3137146543028786,0.3517902024443269,0.007005063517295965,-0.1105898333406624,-2.410912585707365}    
    u8defu70b9_29_q = {-1.597585132756626,-0.01977670808513686,2.761443760346299,1.293093490211331,-1.645703190615213,0.7563223928991486}    
    u8defu70b9_30_p = {-1.031347443991746,-0.5351123365518067,0.8565444671385485,-0.04085427992158362,0.2099798811967215,2.457552666581699}    
    u8defu70b9_30_q = {-2.473379147062982,-0.7633223404328665,0.5686518899414893,-0.3236257324961886,-1.374263180764322,0.2301531447638779}    
    u8defu70b9_31_p = {-0.7735057684013518,-0.5479836175801208,0.02630394312495095,-0.04084718787480027,0.2101300530855461,2.457613431133851}    
    u8defu70b9_31_q = {-2.291836824063151,-1.053572431091336,1.6546776079167,1.090340718667191,-1.363533077968181,0.04283670882254028}    
    u8defu70b9_32_p = {-0.773508541048323,-0.6309146779691055,0.02631135723203398,-0.0408361835566625,0.2101410585002254,2.457615523485698}    
    u8defu70b9_32_q = {-2.235692789717012,-1.092079567736319,1.540103188341533,1.026180158100181,-1.360999056459832,-0.01431310390597454}    
    u8defu70b9_33_p = {-0.7735173365284062,-0.3388456792331413,0.02628982411596881,-0.040850450956575,0.2101894083700375,2.45759481484887}    
    u8defu70b9_33_q = {-2.467390378064028,-0.9882103366178629,1.875606901893968,1.209897392474519,-1.375490365394631,0.2213090451894542}    
    u8defu70b9_34_p = {-1.017470309087215,-0.3388582147200661,0.923707638350045,-0.04078389126759769,0.2102157512348635,2.457679375739514}    
    u8defu70b9_34_q = {-2.615971520921965,-0.5772681901123633,0.7630552895084429,-0.3424088125418238,-1.387872914821682,0.3744924679205717}    
    u8defu70b9_35_p = {-1.031018008790453,-0.1980147911216195,0.9237064648609535,-0.04077318518951912,0.2102362541328911,2.457689458514971}    
    u8defu70b9_35_q = {-2.744802956456707,-0.5268645177553024,0.8388285876962984,-0.3394940802900789,-1.403776363606098,0.5042230288280153}    
    u8defu70b9_36_p = {-0.8018500433725961,-0.1980257424899196,0.1967615868852705,-0.0407736688633282,0.2103132570880432,2.457735108040016}    
    u8defu70b9_36_q = {-2.63408228199522,-0.7075549667158324,1.980128324144083,1.00213867966615,-1.391196708616863,0.3899679546281916}    
    u8defu70b9_37_p = {-0.8018766478174163,-0.04038349680176474,0.1967669867189461,-0.04068413004200225,0.2104193871248887,2.457749269901425}    
    u8defu70b9_37_q = {-2.82099505654551,-0.6839320000919178,2.02963829359551,0.9965832728963816,-1.415775502213559,0.577862206875109}    
    u8defu70b9_38_p = {-1.04860310028896,-0.01735138842876811,0.8680664016710427,-0.04068195490123334,0.2103563038237442,2.45791219517064}    
    u8defu70b9_38_q = {-2.920282258362242,-0.5055150152869869,0.9610703757054596,-0.2653675384899145,-1.429733546099984,0.6798265342384874}    
    u8defu70b9_39_p = {-1.048624606015717,0.1436677898321037,0.8680435303482958,-0.04068355140344082,0.2103699728423886,2.457922294667901}    
    u8defu70b9_39_q = {-3.077282238794,-0.5226929000351118,0.9314398957519867,-0.2974970951639654,-1.456819360443086,0.8358598873926865}    
    u8defu70b9_40_p = {-0.7440292259237584,0.1436870017766817,0.1675267122473703,-0.04062070432948402,0.2104949660309194,2.45791332027135}    
    u8defu70b9_40_q = {-3.050278776774824,-0.6950603641267177,2.115310204999739,1.062091171484346,-1.453442915162116,0.806314303636579}    
    u8defu70b9_41_p = {-0.7920926007056412,0.3353188085296664,0.1701406175261081,-0.04054218153262341,0.2104524559915732,2.457959748240772}    
    u8defu70b9_41_q = {-3.299765817127974,-0.7574051234530621,1.916708008433218,0.9025922705347654,-1.500838702638728,1.052732707394909}    
    u8defu70b9_42_p = {-0.7683213400630319,0.3353348474071131,-0.2315771075182812,-0.01240334628862185,0.213964611538035,2.590855462951851}    
    u8defu70b9_42_q = {-3.304443699134595,-1.367684445116915,1.676576486631838,1.272347454772441,-1.503548229099707,1.188087527015076}    
    u8defu70b9_43_p = {-1.053951625615558,0.3304341887868105,1.006062696140697,-0.1324574156927555,0.234112911278281,2.428518717904963}    
    u8defu70b9_43_q = {-3.260521559681947,-0.7671051471810783,0.2557333319084693,-0.8138839672472938,-1.550952116804902,0.9947593714271332}    
    u8defu70b9_44_p = {-0.9911112689096268,0.5221503325686914,0.9918006066800902,-0.02700613212278182,0.3902816968146147,2.363403748835081}    
    u8defu70b9_44_q = {-3.432551514249266,-0.814237677228747,0.168511944960922,-0.9469477722165985,-1.415585146841861,1.117022871619245}    
    u8defu70b9_45_p = {-0.8196698055504709,0.5044968962036971,0.6417751421934077,-0.2016467545448241,0.3041129258623964,2.373658904734258}    
    u8defu70b9_45_q = {-3.490497849455098,-0.3795753613563379,1.488454379194673,-0.05889406195003143,-1.631835599281298,1.169286896474178}    
    u8defu70b9_46_p = {-0.7317719473497949,0.5045201259648794,-0.1645423253853387,-0.2015241797355807,0.3041651818127422,2.373656078877719}    
    u8defu70b9_46_q = {-3.526705871220636,-1.246534726354951,1.686024343326519,1.007881741731422,-1.647575693455959,1.202023970291946}    
    u8defu70b9_47_p = {-0.8196709312416681,0.5044952687142513,0.6417691012314938,-0.2016377889354781,0.3041174213656264,2.373670790433727}    
    u8defu70b9_47_q = {-3.490495149378904,-0.3795780614325322,1.488461140542499,-0.05888461168335139,-1.631828849090812,1.169296346740858}    
    u8defu70b9_48_p = {-0.8196711502659731,0.9599204419390872,0.6417749579772598,-0.2016356220299371,0.3041106254350447,2.373672508323243}    
    u8defu70b9_48_q = {-3.859900673749418,-0.9423130914290858,0.5602171085293137,-0.3800019733950371,-1.756476516562489,1.522178754840364}    
    u8defu70b9_49_p = {-0.7771729471517373,0.3823755626413947,0.4918887740610801,-0.20160433105027,0.3041948761870198,2.373684678684941}    
    u8defu70b9_49_q = {-3.368278900520192,-0.3393847272042098,1.822470596225523,0.2301355942686149,-1.588584428762933,1.054051694615824}    
    u8defu70b9_50_p = {-0.202031601195922,-0.3137150655446357,0.3517908225350475,0.007003108387449321,-0.1105935561863775,-2.410912705445757}    
    u8defu70b9_50_q = {-1.597585132756626,-0.01977535804703971,2.761442633454995,1.293092140173234,-1.645707240729505,0.7563223928991486}    
    u8defu70b9_51_p = {-0.9154727299607348,-0.5351276764791039,0.5876778752320185,-0.04086371757662945,0.210013767782476,2.457601037220077}    
    u8defu70b9_51_q = {-2.404941665804204,-0.5929745333345957,1.313475205038765,0.2649058254606895,-1.368371614508364,0.1588535827391435}    
    u8defu70b9_52_p = {-0.7427456780215518,-0.5351355829651512,0.3192900469957785,-0.04084346853309413,0.2100832765339368,2.457638495682798}    
    u8defu70b9_52_q = {-2.275385259811292,-0.6396561506578166,1.782685698729616,0.8079964511056268,-1.361439168879503,0.02567637456967834}    
    
    
    function str_cat(str1, str2)
        return tostring(str1) .. tostring(str2)
    end
    
    local function calculate_point_to_move_towards(feature, direction, position_distance)
        local posDir={direction[1], direction[2], direction[3]}
        if (math.norm(posDir) < 1e-6) then
            return getTargetTcpPose()
        end
        local direction_vector_normalized=math.normalize(posDir)
        local displacement_pose={direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,direction_vector_normalized[3] * position_distance,0,0,0}

        local wanted_displacement_in_base_frame=poseSub(poseTrans(feature, displacement_pose), feature)
        return poseAdd(getTargetTcpPose(), wanted_displacement_in_base_frame)
    end
    setPlanContext(sched.current_thread_id(), 2, "机器人编程")
    setPlanContext(sched.current_thread_id(), 3, "关节运动")
    setPlanContext(sched.current_thread_id(), 4, "路点_0")
    moveJoint(inverseKinematics(u8defu70b9_0_q, u8defu70b9_0_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 5, "Seeragv  Move To: LM1 backward")
    function waitForMotionComplete()
      sleep(0)
    end
    waitForMotionComplete()
    agv.robot_task_gotarget_req("LM1",-2147483648,-2147483648,-2147483648,-2147483648,"backward")
    while true do
        if (agv.robot_status_task_req()=="COMPLETED") then
            print("Navigation has completed.")
            break
        else
            sleep(0.1)
            print("Navigation is running...")
        end
    end
    
    setPlanContext(sched.current_thread_id(), 6, "Seeragv  Move To: LM2 forward")
    function waitForMotionComplete()
      sleep(0)
    end
    waitForMotionComplete()
    agv.robot_task_gotarget_req("LM2",-2147483648,-2147483648,-2147483648,-2147483648,"forward")
    while true do
        if (agv.robot_status_task_req()=="COMPLETED") then
            print("Navigation has completed.")
            break
        else
            sleep(0.1)
            print("Navigation is running...")
        end
    end
    
    setPlanContext(sched.current_thread_id(), 7, "关节运动")
    setPlanContext(sched.current_thread_id(), 8, "路点_1")
    moveJoint(inverseKinematics(u8defu70b9_1_q, u8defu70b9_1_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 9, "直线运动")
    setPlanContext(sched.current_thread_id(), 10, "路点_27")
    moveLine(u8defu70b9_27_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 11, "直线运动")
    setPlanContext(sched.current_thread_id(), 12, "路点_28")
    moveLine(u8defu70b9_28_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 13, "直线运动")
    setPlanContext(sched.current_thread_id(), 14, "路点_3")
    moveLine(u8defu70b9_3_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 15, "直线运动")
    setPlanContext(sched.current_thread_id(), 16, "路点_4")
    moveLine(u8defu70b9_4_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 17, "直线运动")
    setPlanContext(sched.current_thread_id(), 18, "路点_5")
    moveLine(u8defu70b9_5_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 19, "直线运动")
    setPlanContext(sched.current_thread_id(), 20, "路点_21")
    moveLine(u8defu70b9_21_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 21, "直线运动")
    setPlanContext(sched.current_thread_id(), 22, "路点_22")
    moveLine(u8defu70b9_22_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 23, "关节运动")
    setPlanContext(sched.current_thread_id(), 24, "路点_23")
    moveJoint(inverseKinematics(u8defu70b9_23_q, u8defu70b9_23_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 25, "直线运动")
    setPlanContext(sched.current_thread_id(), 26, "路点_24")
    moveLine(u8defu70b9_24_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 27, "直线运动")
    setPlanContext(sched.current_thread_id(), 28, "路点_25")
    moveLine(u8defu70b9_25_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 29, "关节运动")
    setPlanContext(sched.current_thread_id(), 30, "路点_26")
    moveJoint(inverseKinematics(u8defu70b9_26_q, u8defu70b9_26_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 31, "Seeragv  Move To: LM3 forward")
    function waitForMotionComplete()
      sleep(0)
    end
    waitForMotionComplete()
    agv.robot_task_gotarget_req("LM3",-2147483648,-2147483648,-2147483648,-2147483648,"forward")
    while true do
        if (agv.robot_status_task_req()=="COMPLETED") then
            print("Navigation has completed.")
            break
        else
            sleep(0.1)
            print("Navigation is running...")
        end
    end
    
    setPlanContext(sched.current_thread_id(), 32, "关节运动")
    setPlanContext(sched.current_thread_id(), 33, "路点_6")
    moveJoint(inverseKinematics(u8defu70b9_6_q, u8defu70b9_6_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 34, "直线运动")
    setPlanContext(sched.current_thread_id(), 35, "路点_7")
    moveLine(u8defu70b9_7_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 36, "直线运动")
    setPlanContext(sched.current_thread_id(), 37, "路点_8")
    moveLine(u8defu70b9_8_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 38, "直线运动")
    setPlanContext(sched.current_thread_id(), 39, "路点_9")
    moveLine(u8defu70b9_9_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 40, "直线运动")
    setPlanContext(sched.current_thread_id(), 41, "路点_10")
    moveLine(u8defu70b9_10_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 42, "直线运动")
    setPlanContext(sched.current_thread_id(), 43, "路点_11")
    moveLine(u8defu70b9_11_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 44, "直线运动")
    setPlanContext(sched.current_thread_id(), 45, "路点_12")
    moveLine(u8defu70b9_12_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 46, "直线运动")
    setPlanContext(sched.current_thread_id(), 47, "路点_13")
    moveLine(u8defu70b9_13_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 48, "直线运动")
    setPlanContext(sched.current_thread_id(), 49, "路点_14")
    moveLine(u8defu70b9_14_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 50, "直线运动")
    setPlanContext(sched.current_thread_id(), 51, "路点_15")
    moveLine(u8defu70b9_15_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 52, "直线运动")
    setPlanContext(sched.current_thread_id(), 53, "路点_16")
    moveLine(u8defu70b9_16_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 54, "直线运动")
    setPlanContext(sched.current_thread_id(), 55, "路点_17")
    moveLine(u8defu70b9_17_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 56, "直线运动")
    setPlanContext(sched.current_thread_id(), 57, "路点_18")
    moveLine(u8defu70b9_18_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 58, "直线运动")
    setPlanContext(sched.current_thread_id(), 59, "路点_19")
    moveLine(u8defu70b9_19_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 60, "直线运动")
    setPlanContext(sched.current_thread_id(), 61, "路点_20")
    moveLine(u8defu70b9_20_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 62, "直线运动")
    setPlanContext(sched.current_thread_id(), 63, "路点_2")
    moveLine(u8defu70b9_2_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 64, "关节运动")
    setPlanContext(sched.current_thread_id(), 65, "路点_29")
    moveJoint(inverseKinematics(u8defu70b9_29_q, u8defu70b9_29_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 66, "Seeragv  Move To: LM4 forward")
    function waitForMotionComplete()
      sleep(0)
    end
    waitForMotionComplete()
    agv.robot_task_gotarget_req("LM4",-2147483648,-2147483648,-2147483648,-2147483648,"forward")
    while true do
        if (agv.robot_status_task_req()=="COMPLETED") then
            print("Navigation has completed.")
            break
        else
            sleep(0.1)
            print("Navigation is running...")
        end
    end
    
    setPlanContext(sched.current_thread_id(), 67, "关节运动")
    setPlanContext(sched.current_thread_id(), 68, "路点_30")
    moveJoint(inverseKinematics(u8defu70b9_30_q, u8defu70b9_30_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 69, "直线运动")
    setPlanContext(sched.current_thread_id(), 70, "路点_51")
    moveLine(u8defu70b9_51_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 71, "直线运动")
    setPlanContext(sched.current_thread_id(), 72, "路点_52")
    moveLine(u8defu70b9_52_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 73, "关节运动")
    setPlanContext(sched.current_thread_id(), 74, "路点_31")
    moveJoint(inverseKinematics(u8defu70b9_31_q, u8defu70b9_31_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 75, "直线运动")
    setPlanContext(sched.current_thread_id(), 76, "路点_32")
    moveLine(u8defu70b9_32_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 77, "直线运动")
    setPlanContext(sched.current_thread_id(), 78, "路点_33")
    moveLine(u8defu70b9_33_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 79, "直线运动")
    setPlanContext(sched.current_thread_id(), 80, "路点_34")
    moveLine(u8defu70b9_34_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 81, "直线运动")
    setPlanContext(sched.current_thread_id(), 82, "路点_35")
    moveLine(u8defu70b9_35_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 83, "直线运动")
    setPlanContext(sched.current_thread_id(), 84, "路点_36")
    moveLine(u8defu70b9_36_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 85, "直线运动")
    setPlanContext(sched.current_thread_id(), 86, "路点_37")
    moveLine(u8defu70b9_37_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 87, "直线运动")
    setPlanContext(sched.current_thread_id(), 88, "路点_38")
    moveLine(u8defu70b9_38_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 89, "直线运动")
    setPlanContext(sched.current_thread_id(), 90, "路点_39")
    moveLine(u8defu70b9_39_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 91, "直线运动")
    setPlanContext(sched.current_thread_id(), 92, "路点_40")
    moveLine(u8defu70b9_40_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 93, "直线运动")
    setPlanContext(sched.current_thread_id(), 94, "路点_41")
    moveLine(u8defu70b9_41_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 95, "直线运动")
    setPlanContext(sched.current_thread_id(), 96, "路点_42")
    moveLine(u8defu70b9_42_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 97, "直线运动")
    setPlanContext(sched.current_thread_id(), 98, "路点_43")
    moveLine(u8defu70b9_43_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 99, "关节运动")
    setPlanContext(sched.current_thread_id(), 100, "路点_44")
    moveJoint(inverseKinematics(u8defu70b9_44_q, u8defu70b9_44_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 101, "直线运动")
    setPlanContext(sched.current_thread_id(), 102, "路点_45")
    moveLine(u8defu70b9_45_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 103, "直线运动")
    setPlanContext(sched.current_thread_id(), 104, "路点_46")
    moveLine(u8defu70b9_46_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 105, "直线运动")
    setPlanContext(sched.current_thread_id(), 106, "路点_47")
    moveLine(u8defu70b9_47_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 107, "直线运动")
    setPlanContext(sched.current_thread_id(), 108, "路点_48")
    moveLine(u8defu70b9_48_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 109, "直线运动")
    setPlanContext(sched.current_thread_id(), 110, "路点_49")
    moveLine(u8defu70b9_49_p, 1.2, 0.25, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 111, "关节运动")
    setPlanContext(sched.current_thread_id(), 112, "路点_50")
    moveJoint(inverseKinematics(u8defu70b9_50_q, u8defu70b9_50_p), 1.39626, 1.0472, 0, 0)
    
    setPlanContext(sched.current_thread_id(), 113, "Seeragv  Move To: LM1 backward")
    function waitForMotionComplete()
      sleep(0)
    end
    waitForMotionComplete()
    agv.robot_task_gotarget_req("LM1",-2147483648,-2147483648,-2147483648,-2147483648,"backward")
    while true do
        if (agv.robot_status_task_req()=="COMPLETED") then
            print("Navigation has completed.")
            break
        else
            sleep(0.1)
            print("Navigation is running...")
        end
    end
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_zx()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app


